# Generated by Django 3.2.18 on 2023-04-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_auto_20230406_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_session',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
