# Generated by Django 3.2.18 on 2023-04-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_auto_20230406_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_session',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
