# Generated by Django 3.2.18 on 2023-04-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_auto_20230406_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_session',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
